### ISSUE TITLE
preserve comments

### ISSUE THREAD

**Issue by jmuffat** [liamcurry/gql#1]
Not sure if it is a big deal, but I wouldn't mind if we could preserve those comments that are used to generate the descriptions in graphiql. 

Thanks
J;

**Comment by nicka** [comment]
Same here 👍

**Comment by liamcurry** [comment]
Yep totally agree. I just published new versions of `gql-format` and `gql-merge` that should preserve comments, along with a couple bugfixes. Please let me know if you find any issues/bugs. Thanks!
